spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://127.0.0.1:3306/eventuate
    username: mysqluser
    password: mysqlpw
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
  main:
    allow-bean-definition-overriding: true
server:
  port: 9090
  
tmbr-customer-api: ${DOCKER_HOST_IP:localhost}:7070
tmbr-event-api: ${DOCKER_HOST_IP:localhost}:8080
tmbr-event-master-api: ${DOCKER_HOST_IP:localhost}:9090
eventuatelocal.kafka.bootstrap.servers: ${DOCKER_HOST_IP:localhost}:9092
eventuatelocal.zookeeper.connection.string: ${DOCKER_HOST_IP:localhost}:2181

logging.level.org.springframework.orm.jpa: INFO
logging.level.org.hibernate.SQL: INFO
logging.level.io.eventuate: INFO

eventuatelocal.cdc.db.user.name: root
eventuatelocal.cdc.db.password: rootpassword