apiVersion: v1
kind: Service
metadata:
  name: tmbr-event-master-api
  labels:
    app: tmbr-event-master-api
spec:
  ports:
  - name: http #http로  
    port: 80 #80으로 편함  
    targetPort: 9090
    nodePort: 31583
  selector:
    app: tmbr-event-master-api
  type: NodePort
#NodePort
